name: Windows RDP with NoVNC

on:
  workflow_dispatch:

jobs:
  rdp-with-novnc:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          choco install tightvnc --force --yes

      - name: Configure and start TightVNC Server
        run: |
          $password = "yourpassword"
          $vncpasswd = "${password}"
          $vncpasswd += "`0"
          $vncpasswd | Out-File -Encoding ASCII -FilePath vncpasswd.txt
          & "C:\Program Files\TightVNC\tvnserver.exe" -install
          & "C:\Program Files\TightVNC\tvnserver.exe" -start
          & "C:\Program Files\TightVNC\tvncpasswd.exe" -f vncpasswd.txt
          Remove-Item -Path vncpasswd.txt

      - name: Setup NoVNC
        run: |
          git clone https://github.com/novnc/noVNC.git
          cd noVNC
          npm install
          npm run build

      - name: Run NoVNC (websockify)
        run: |
          pip install websockify
          websockify 6080 localhost:5900 &
          Start-Process -FilePath "C:\Program Files\TightVNC\tvnviewer.exe" -ArgumentList "localhost:5900" -WindowStyle Hidden

      - name: Keep the session alive
        run: |
          while ($true) {
            Start-Sleep -Seconds 60
          }
