name: Ubuntu VM with GUI

on: push  # Trigger on every push

jobs:
  build-and-run-gui:
    name: Run Ubuntu with GUI
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build Docker Image
      id: build
      run: |
        docker build -t ubuntu-gui .  # Build the Docker image
        
    - name: Run GUI Application
      run: |
        docker run -it --rm \
          --privileged \
          --net host \
          --env="DISPLAY=$DISPLAY" \
          --env="XAUTHORITY=$XAUTHORITY" \
          --volume="/tmp/.X11-unix:/tmp/.X11-unix" \
          ubuntu-gui  # Replace with your Docker image name

    - name: Install Additional GUI Applications (Optional)
      run: |
        docker exec -it $(docker ps -lq) \
          apt-get install -y --no-install-recommends firefox  # Install additional apps if needed
