name: Ubuntu VM with GUI

on: push

env:
  TZ: "UTC"

jobs:
  build-and-run-gui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
          docker --version
      
      # Set up Docker permissions
      - name: Set up Docker permissions
        run: |
          sudo usermod -aG docker $USER
          newgrp docker
      
      # Install required tools (e.g., X display server for GUI)
      - name: Install X display server
        run: |
          sudo apt-get install -y xserver-xorg xterm
          sudo bash -c "echo 'export DISPLAY=:0' >> /etc/profile"
          sudo bash -c "echo 'Xorg /usr/share/X11/xorg.conf.d Duck.FloatTensor' >> /etc/X11/xorg.conf"
          startx &
      
      # Run a GUI application (e.g., a simple browser)
      - name: Run browser in Docker
        run: |
          docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --net host -it ubuntu:latest /bin/bash -c "|
            apt-get update && 
            apt-get install -y chromium-browser && 
            chromium-browser --no-sandbox"
      
      # Optional: Run your custom GUI application here
      - name: Run custom GUI application
        run: |
          # Replace this with your GUI application commands
          echo "Running custom GUI application..."
